### ISSUE TITLE
Export word list

### ISSUE THREAD

**Issue by aloglu** [willhains/Kotoba#29]
Would you consider integrating an export function into the app?

In my own crude way, I tried to accomplish this by downloading the app's container via Xcode and browsing through the files, but to no avail. If there ever comes a point where the app is no longer supported, I wouldn't want the words I've accumulated to disappear along with it.

I found the app based on @gruber's recommendation and I've been using it incessantly ever since. Your work is much appreciated. Thank you.

**Comment by willhains** [comment]
Good idea.

**Comment by willhains** [comment]
@aloglu This is finally done! Tap the share button on the History screen to open the share sheet. Let me know if you like it! 😊
