### ISSUE TITLE
Hard to touch done button when done

### ISSUE THREAD

**Issue by zj299792458** [willhains/Kotoba#37]
Please use UINavigationController to push the UIReferenceLibraryViewController, instead of modally present. Considering current iPhone's screen can be up to 5.8 inch, the done button is really hard to reach.

in UIViewController+Dictionary.swift
'''
navigationController?.pushViewController(dictionaryViewController, animated: true)
//        present(dictionaryViewController, animated: true, completion: nil)
""

So that we can get back to main view controller by swiping

Thank you.

**Comment by willhains** [comment]
That does sound like a good idea. Unfortunately, it doesn't work. It seems iOS hard-wires the dictionary view controller to slide up from the button; even if I push it to the navigation controller (I copied & pasted your code snippet).

However, it seems that iOS 13 presents the dictionary view as a card, and you can swipe downwards anywhere to dismiss it; no need to reach up to the Done button.
