### ISSUE TITLE
Searches are slow on iOS 13

### ISSUE THREAD

**Issue by seiz** [willhains/Kotoba#39]
Hi,

when i type in a word and then click Search, Kotoba reacts rather slow and slugish, when run on iOS 13. Any updates for iOS 13 in sight (i am not a developer which could fix this)?

Thanks for such a useful App!

**Comment by willhains** [comment]
First of all, thanks for using my app, and for the kind words.

Yes, I’m planning an update after macOS Catalina ships. However, I suspect the delay you’re seeing is caused by iOS 13 itself, and there may not be anything I can do about it. I’ll check this, and submit a bug report to Apple. Cheers.

**Comment by willhains** [comment]
This is a regression in iOS 13 (one of many!), but @chockenberry kindly donated a clever solution in #41 which helps a lot. It's still not as fast as it was on iOS 12, but I think this is the best we can do for now.
