### ISSUE TITLE
Dark Mode text is invisible when typing

### ISSUE THREAD

**Issue by kimonostereo** [willhains/Kotoba#40]
When in dark mode, the text typed for search as well as text in the history section is not shown or maybe it's white and I can't see it?

**Comment by willhains** [comment]
@kimonostereo Thanks for the bug report!
Hmm... works for me. Can you post a screenshot? (Blur/block out things you don’t want to be visible.)

**Comment by kimonostereo** [comment]
@willhains I made a video of what I'm seeing. Maybe I'm doing something wrong on my end?
[Dark Mode invisible issue](http://go.hensh.in/RPReplay_Final1573610687/)

**Comment by willhains** [comment]
Thank you so much for that. I can reproduce it. Shouldn’t be difficult to fix; I’ll take a look this weekend. Thanks again!

**Comment by willhains** [comment]
Before I got a chance to finish my fix for this, @chockenberry fixed it, along with some other stuff, in #41!
