### ISSUE TITLE
Ignore multiline pasteboard text at launch

### ISSUE THREAD

**Issue by willhains** [willhains/Kotoba#43]
The new feature added in #41 to automatically detect text on the pasteboard, and offer to use it as a search, should ignore pasteboard text that contains newline characters, as it is unlikely to be useful as a word search.

**Comment by chockenberry** [comment]
I did this in my latest pull request (#45).

**Comment by willhains** [comment]
I have another idea for a useful way to handle the pasteboard. I'm attempting this locally now...

1. Read the pasteboard at launch, and monitor changes to it.
2. Split the pasteboard string into words by whitespace (including newlines).
3. Filter for simple words ("of", "and", "to", etc.).
4. Filter for tokens that are unlikely to be words, or likely to be passwords, e.g. containing a symbol or digit character.
5. Display words as a list, underneath the "Type a Word" text entry field.

Motivations / expected benefits:

- No extra taps or interruptions for the user upon launch. They can tap a word from the pasteboard, or just start typing as before.
- When used in iPad multitasking (SlideOver, split screen), the user can simply select and copy text in the other window, and instantly see Kotoba update to show the copied words. One tap to see the definition.
- I'm even considering moving the history into this list, as a separate section, making this effectively a one-screen app. Even fewer taps to get to what you want. (Possible privacy issue?)

**Comment by willhains** [comment]
Reminder to self: Make sure the filtering of the token list doesn't mess up non-English/non-Latin-based languages. Also, how to tokenise languages that don't use whitespace as a word separator (close to my heart: Japanese).

**Comment by chockenberry** [comment]
I like this idea: anything that gets rid of an alert is a good thing. Also solves the issue of multiple prompts for same clipboard contents.

You’ll need to do it at app activation, not launch, though. Kotoba can hang around in memory for quite awhile (small footprint).

I think putting history on the first screen will just add noise. Love the simplicity of *Type a Word”.

**Comment by chockenberry** [comment]
Let me know when you're done with this work - I have some ideas how to improve it.

**Comment by chockenberry** [comment]
Overall, this is a very elegant way to handle the data detection. Good work!

**Comment by willhains** [comment]
Yes, I realised the problems with using TVC pretty soon after I got it working. I’ll change it to an embedded view, and keep the “Type a Word” visible always. That should always be the primary way to use the app, and should therefore have visual priority as well.

**Comment by chockenberry** [comment]
Here you go: https://github.com/willhains/Kotoba/pull/47

**Comment by willhains** [comment]
Outstanding:
- [ ] ignore probable passwords
- [ ] ignore trivial words ("of", "and", etc.)
