### ISSUE TITLE
Searches are still too slow on iOS 13

### ISSUE THREAD

**Issue by willhains** [willhains/Kotoba#64]
Opening this issue to track the problem, although it's really an iOS 13 bug. Originally reported in #39, and @chockenberry implemented a workaround using background queues to do the lookup, but it's not ideal, and the delay is still much worse than it was on iOS 12.

This issue is to file a radar with Apple, but also track the problem/workarounds on the Kotoba side.

**Comment by exgphe** [comment]
I think it's fixed in iOS 14

**Comment by willhains** [comment]
You know what? I think you're right. Yay! 🎉

I will close this issue then.
