### ISSUE TITLE
Clipboard and Text File buttons in Settings can't handle long labels

### ISSUE THREAD

**Issue by chockenberry** [willhains/Kotoba#66]
The new layout of the import buttons in Settings looks much better, but there's a problem: the secondary label doesn't wrap or shrink. The contents of this button can be long in English (e.g. "12,345 words", and even longer in other languages (e.g. CHOCK). Not the end of the world, but we've come this far :-)

**Comment by willhains** [comment]
Thanks for catching this. It’s easy to fix, so I’ve added it to the 2.0 list.

**Comment by willhains** [comment]
I think this is resolved now. Let me know if you notice any others like this.
